### ISSUE TITLE
Transaction cost exceeds current gas limit.

### ISSUE THREAD

**Issue by charry1729** [rstormsf/ico_per_week#1]
truffle migrate
Using network 'development'.
Running migration: 1_initial_migration.js
Deploying Migrations...
... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Transaction cost exceeds current gas limit. Limit: 4709181, got: 6721975. Try decreasing supplied gas.
at Object.InvalidResponse (/home/demo/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
at /home/demo/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:331156:36
at /home/demo/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:175492:11
though i changes in the truffle.js .. to different values .. it dinthelp
truffle console
truffle(development)> web3.eth.getBlock("latest").gasLimit
4712388

**Comment by charry1729** [comment]
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      gas: 4600000,
      network_id: "*" // Match any network id
    }
  }
};
